apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: expense-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - project: expense
          env: dev
          component: backend
        - project: expense
          env: dev
          component: frontend
        - project: expense
          env: dev
          component: database

  template:
    metadata:
      name: "{{project}}-{{env}}-{{component}}"
      namespace: argocd
      labels:
        env: "{{env}}"
        project: "{{project}}"
        component: "{{component}}"
        app.kubernetes.io/part-of: "{{project}}"

      annotations:
        # ðŸ”¹ SYNC WAVES (CRITICAL)
        argocd.argoproj.io/sync-wave: >
          {{- if eq .component "database" -}}0
          {{- else if eq .component "backend" -}}1
          {{- else if eq .component "frontend" -}}2
          {{- else -}}3
          {{- end }}


        # ðŸ”¹ Notifications
        #notifications.argoproj.io/subscribe.on-deployed.email: "expense-{{env}}-{{path.basename}}@example.com"
        #notifications.argoproj.io/subscribe.on-health-degraded.email: "expense-{{env}}-{{path.basename}}@example.com"
        #notifications.argoproj.io/subscribe.on-sync-failed.email: "expense-{{env}}-{{path.basename}}@example.com"

    spec:
      project: "{{project}}"         # This name should match with the name of 'AppProject' created previously

      source:
        repoURL: https://github.com/vaheedgithubac/expense.git
        targetRevision: main
        path: app-code/{{component}}/CI-CD/CD/helm  #"{{path}}/helm"
        helm:
          releaseName: "{{project}}-{{env}}-{{component}}"  # must be <= 53 chars
          valueFiles:
            - values-dockerHub.yml

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{project}}-{{env}}"

      syncPolicy:
        automated:
          prune: true          # delete resources not in Git
          selfHeal: true       # revert out-of-band changes
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true



      #syncPolicy:
      #  {{- if ne .component "database" }}
      #  automated:
      #    prune: true
      #    selfHeal: true
      #  {{- else }}
      #  automated:
      #    selfHeal: true
      #  {{- end }}
