apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: expense-applicationset-dev
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - env: dev
              #- env: stage
              #- env: prod
        - list:
            elements:
              - component: database
  template:
    metadata:
      name: expense-{{env}}-{{component}}
      namespace: argocd
      labels:
        env: "{{env}}"
        project: expense
        component: "{{component}}"
        app.kubernetes.io/part-of: expense

      annotations:
        # ðŸ”¹ SYNC WAVES (CRITICAL)
        argocd.argoproj.io/sync-wave: >
          {{- if eq .component "database" -}}0
          {{- else if eq .component "backend" -}}1
          {{- else if eq .component "frontend" -}}2
          {{- else -}}3
          {{- end }}


        # ðŸ”¹ Notifications
        #notifications.argoproj.io/subscribe.on-deployed.email: "expense-{{env}}-{{path.basename}}@example.com"
        #notifications.argoproj.io/subscribe.on-health-degraded.email: "expense-{{env}}-{{path.basename}}@example.com"
        #notifications.argoproj.io/subscribe.on-sync-failed.email: "expense-{{env}}-{{path.basename}}@example.com"

    spec:
      project: expense         # This is the name of 'AppProject' created previously

      source:
        repoURL: https://github.com/vaheedgithubac/expense.git
        targetRevision: main
        path: app-code/{{component}}/CI-CD/CD/helm  #"{{path}}/helm"    # Chart.yml path
        helm:
          valueFiles:
            - values-dockerHub.yml

      destination:
        server: https://kubernetes.default.svc
        namespace: "expense-{{env}}"

      syncPolicy:
        automated:
          prune: true          # delete resources not in Git
          selfHeal: true       # revert out-of-band changes
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
